"use client";

import { useState } from "react";

type Assignment = { id: string; week: number; partner: string; complete: boolean };

export function DateFeedbackMatrix({ assignments }: { assignments: Assignment[] }) {
  const [selected, setSelected] = useState<Assignment | null>(null);
  const maxWeek = Math.max(5, ...assignments.map((item) => item.week));

  return <div className="mt-5"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-xs font-bold uppercase tracking-wide text-[#90777d]">Date feedback progress</p><p className="text-xs text-[#806d72]"><span className="mr-1 inline-block h-2.5 w-2.5 rounded-sm bg-[#d7d7d7]" />Needed <span className="ml-3 mr-1 inline-block h-2.5 w-2.5 rounded-sm bg-[#67b96a]" />Submitted</p></div><div className="mt-3 overflow-x-auto"><div className="grid min-w-max grid-flow-col auto-cols-[4.25rem] gap-3">{Array.from({ length: maxWeek }, (_, index) => { const week = index + 1; const weekAssignments = assignments.filter((item) => item.week === week); return <div key={week} className="text-center"><p className="mb-2 text-xs font-bold text-[#665b5d]">Week {week}</p><div className="flex min-h-9 justify-center gap-1.5">{weekAssignments.length ? weekAssignments.map((assignment) => <button key={assignment.id} type="button" onClick={() => setSelected(assignment)} title={`${assignment.partner}: ${assignment.complete ? "feedback submitted" : "feedback needed"}`} aria-label={`Week ${assignment.week}, ${assignment.partner}: ${assignment.complete ? "feedback submitted" : "feedback needed"}`} className={`h-7 w-7 rounded-md border-2 border-white shadow-sm transition focus:outline-none focus:ring-2 focus:ring-[#7d1d2b] focus:ring-offset-2 ${assignment.complete ? "bg-[#67b96a] hover:bg-[#4c9d54]" : "bg-[#d7d7d7] hover:bg-[#c2c2c2]"}`} />) : <span title={`Week ${week}: no date assigned`} className="h-7 w-7 rounded-md bg-[#f1eeee]" />}</div></div>; })}</div></div><p className="mt-3 text-xs text-[#806d72]">Hover or select a box to see the sister-date details.</p>{selected && <div className="mt-4 rounded-xl bg-[#fcf5f6] p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-bold text-[#4a3036]">Week {selected.week}: {selected.partner}</p><p className="mt-1 text-sm text-[#655258]">{selected.complete ? "Feedback submitted — synced from the feedback sheet." : "Feedback needed. This status will update automatically after your form response is recorded."}</p></div><button type="button" onClick={() => setSelected(null)} className="text-sm text-[#806d72]">Close</button></div>{!selected.complete && <a href="https://forms.gle/A2Fw2Po2JUe3b6As7" target="_blank" rel="noreferrer" className="mt-3 inline-block rounded-lg bg-[#7d1d2b] px-3 py-2 text-sm font-bold text-white">Open feedback form</a>}</div>}</div>;
}
