import { CopyCard } from "@/components/nme/page";
import type { MemberDateStatus } from "@/lib/member-progress";

export function SisterDateStatus({ assignments, title = "Your sister-date status", showFeedbackLink = true }: { assignments: MemberDateStatus[]; title?: string; showFeedbackLink?: boolean }) {
  const weeks = [...new Set([1, 2, 3, 4, ...assignments.map((date) => date.week)])].sort((a, b) => a - b);
  const byWeek = weeks.map((week) => assignments.filter((date) => date.week === week));
  const slots = Math.max(3, ...byWeek.map((dates) => dates.length));
  return <div className="min-w-0"><CopyCard title={title}><p className="text-sm text-[#806d72]">Dates will be released the Sunday before the week.</p><div className="overflow-x-auto rounded-xl border border-[#e2dfe1]"><table className="w-full min-w-[640px] table-fixed border-collapse text-left"><caption className="sr-only">Sister dates by week and feedback status</caption><thead><tr className="bg-[#fcf5f6]">{weeks.map((week) => <th key={week} scope="col" className="border-b border-[#e2dfe1] px-4 py-3 font-bold text-[#4a3036]">Week #{week}</th>)}</tr></thead><tbody>{Array.from({ length: slots }, (_, slot) => <tr key={slot}>{byWeek.map((dates, index) => { const date = dates[slot]; return <td key={weeks[index]} className="border-b border-[#e2dfe1] p-3 align-top">{date ? <div className={`rounded-lg border p-3 ${date.complete ? "border-green-200 bg-green-100 text-green-900" : "border-yellow-200 bg-yellow-100 text-yellow-900"}`}><p className="font-bold">{date.partner}</p><p className="mt-1 text-sm font-semibold">{date.complete ? "Feedback submitted" : "Feedback needed"}</p>{showFeedbackLink && <a href="https://forms.gle/A2Fw2Po2JUe3b6As7" target="_blank" rel="noreferrer" className="mt-2 inline-block rounded-md bg-[#7d1d2b] px-3 py-2 text-xs font-semibold text-white">Fill out sister date feedback form</a>}</div> : <p className="rounded-lg bg-[#f4f1ee] p-3 text-sm text-[#806d72]">Not assigned yet</p>}</td>; })}</tr>)}</tbody></table></div></CopyCard></div>;
}
