import Image from "next/image";
import Link from "next/link";

import { Calendar } from "@/components/calendar/calendar";
import { AnnouncementBody } from "@/components/nme/announcement-body";
import { AnnouncementComposer } from "@/components/nme/announcement-composer";
import { getCurrentUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export default async function WelcomePage() {
  const user = await getCurrentUser();
  const [calendarItems, announcements, announcementCount] = await Promise.all([
    prisma.calendarItem.findMany({ orderBy: { dueAt: "asc" } }),
    prisma.announcement.findMany({ orderBy: { createdAt: "desc" }, take: 2 }),
    prisma.announcement.count(),
  ]);
  const items = calendarItems.map((item) => ({ ...item, dueAt: item.dueAt.toISOString() }));

  return <>
    <section className="relative min-h-[38rem] overflow-hidden bg-[#32121f] text-white"><Image src="/images/chapter-group.jpg" alt="MIT Alpha Phi sisters together" fill priority sizes="100vw" className="object-cover object-center" /><div className="absolute inset-0 bg-gradient-to-r from-[#260c18]/90 via-[#421226]/62 to-transparent" /><div className="relative mx-auto flex min-h-[38rem] max-w-7xl items-end px-5 py-14 sm:px-8 sm:py-20"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.24em] text-white/70">MIT Alpha Phi · Zeta Phi Chapter</p><h1 className="mt-5 font-serif text-6xl font-semibold leading-[.86] tracking-tight sm:text-8xl">New Member<br />Education</h1><p className="mt-6 max-w-xl text-base leading-7 text-white/85 sm:text-lg">Welcome to your chapter home for programming, resources, reminders, and the moments that shape your Alpha Phi experience.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/your-profile" className="bg-white px-6 py-3 text-sm font-bold text-[#6f1935] transition hover:bg-[#e3e0e2]">View your profile</Link><a href="https://docs.google.com/spreadsheets/d/1SP6IxSaqmsV8M7iXkREGqlOY5r6goH9FIakCplfZGCo/edit?gid=0#gid=0" target="_blank" rel="noreferrer" className="border border-white/70 px-6 py-3 text-sm font-bold text-white transition hover:bg-white/15">Sign up for office hours</a></div></div></div></section>
    <section className="bg-white"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-14 sm:px-8 lg:grid-cols-[.92fr_1.08fr] lg:items-center lg:py-20"><div className="relative min-h-[30rem] overflow-hidden bg-[#e7e4e3]"><Image src="/images/chapter-campus.jpg" alt="Alpha Phi sisters on the MIT campus" fill sizes="(min-width: 1024px) 42vw, 100vw" className="object-cover object-[50%_55%]" /></div><div className="max-w-xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#6f1935]">Your home under the dome</p><h2 className="mt-4 font-serif text-5xl font-semibold leading-[.9] text-[#342e32]">Everything you need to feel ready to take on MIT!</h2><div className="mt-6 text-base leading-7 text-[#615a5f]"><p>This website contains resources, programming, due dates, reminders, and advice from older APhis covering a lot of helpful information that can improve your MIT experience. We are so so excited to welcome you into our chapter!!</p></div><Link href="/nme-slides" className="mt-7 inline-block border-b-2 border-[#6f1935] pb-1 text-sm font-bold uppercase tracking-[.12em] text-[#6f1935] transition hover:text-[#3f0e20]">Explore NME resources →</Link></div></div></section>
    <section className="bg-[#f4f1ee]"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-14 sm:px-8 lg:grid-cols-[1.15fr_.85fr] lg:py-20"><div className="border-t-4 border-[#6f1935] bg-white p-6 sm:p-8"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#856e77]">From the chapter</p><h2 className="mt-2 font-serif text-4xl font-semibold text-[#342e32]">Recent announcements</h2></div>{announcementCount > 2 && <Link href="/announcements" className="mt-2 text-sm font-bold text-[#6f1935] underline underline-offset-4">View all</Link>}</div>{user?.role === "admin" && user.accessStatus === "approved" && <AnnouncementComposer />}<div className="mt-6 space-y-0 divide-y divide-[#e2dfe1]">{announcements.length ? announcements.map((announcement) => <article key={announcement.id} className="py-5 first:pt-0"><div className="flex items-start justify-between gap-4"><p className="font-serif text-2xl font-semibold leading-none text-[#3b3337]">{announcement.title || "Announcement"}</p><div className="shrink-0 text-right text-xs text-[#806d72]"><p className="font-semibold text-[#655258]">{announcement.authorName}</p><p>{announcement.createdAt.toLocaleString("en-US", { month: "short", day: "numeric", minute: "2-digit" })}</p></div></div><div className="mt-3"><AnnouncementBody body={announcement.body} /></div></article>) : <p className="py-5 text-sm text-[#806d72]">No announcements yet.</p>}</div></div><div className="relative min-h-[30rem] overflow-hidden bg-[#6f1935]"><Image src="/images/chapter-event.jpg" alt="Alpha Phi sisters at a chapter event" fill sizes="(min-width: 1024px) 35vw, 100vw" className="object-cover opacity-85" /><div className="absolute inset-0 bg-[#6f1935]/25" /><div className="absolute bottom-0 left-0 right-0 p-8 text-white"><p className="text-xs font-bold uppercase tracking-[.2em] text-white/75">Zeta Phi</p><p className="mt-2 max-w-sm font-serif text-4xl font-semibold leading-none">We&apos;re so excited to get to know you!</p></div></div></div></section>
    <section className="bg-white"><div className="mx-auto max-w-7xl px-5 py-14 sm:px-8 lg:py-20"><div className="mb-8 max-w-xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#6f1935]">Your schedule</p><h2 className="mt-3 font-serif text-5xl font-semibold leading-none text-[#342e32]">What&apos;s next</h2></div><Calendar items={items} canManageCalendar={user?.role === "admin" && user.accessStatus === "approved"} /></div></section>
  </>;
}
