"use client";

import { useActionState, useMemo, useState } from "react";

import { createCalendarItemAction, deleteCalendarItemAction } from "@/app/actions";

type CalendarItem = { id: string; title: string; location: string | null; type: string; dueAt: string; notes: string | null };
const monthFormatter = new Intl.DateTimeFormat("en-US", { month: "long", year: "numeric" });
const dateFormatter = new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" });

export function Calendar({ items }: { items: CalendarItem[] }) {
  const [month, setMonth] = useState(() => new Date());
  const [selectedDate, setSelectedDate] = useState(() => new Date());
  const [state, formAction, pending] = useActionState(createCalendarItemAction, {});
  const days = useMemo(() => makeDays(month), [month]);
  const selectedItems = items.filter((item) => sameDay(new Date(item.dueAt), selectedDate));

  return <div className="grid gap-6 xl:grid-cols-[1fr_340px]">
    <div className="rounded-2xl border border-[#eadfe1] bg-white p-4 shadow-sm sm:p-6"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#90777d]">Shared chapter calendar</p><h2 className="mt-1 text-2xl font-bold text-[#4a3036]">Calendar</h2></div><div className="flex gap-2"><button className="rounded-lg border border-[#e5d7da] px-3 py-1.5 text-sm font-bold text-[#6f575d] hover:bg-[#fbf5f5]" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1))}>←</button><button className="rounded-lg border border-[#e5d7da] px-3 py-1.5 text-sm font-bold text-[#6f575d] hover:bg-[#fbf5f5]" onClick={() => setMonth(new Date())}>Today</button><button className="rounded-lg border border-[#e5d7da] px-3 py-1.5 text-sm font-bold text-[#6f575d] hover:bg-[#fbf5f5]" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1))}>→</button></div></div><h3 className="mt-7 text-center text-lg font-bold text-[#51383e]">{monthFormatter.format(month)}</h3><div className="mt-4 grid grid-cols-7 text-center text-xs font-bold uppercase tracking-wide text-[#a0888d]">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(day => <div key={day} className="py-2">{day}</div>)}</div><div className="grid grid-cols-7 border-l border-t border-[#f0e7e8]">{days.map((day) => { const dayItems = items.filter((item) => sameDay(new Date(item.dueAt), day.date)); const active = sameDay(day.date, selectedDate); return <button key={day.key} onClick={() => setSelectedDate(day.date)} className={`min-h-20 border-b border-r border-[#f0e7e8] p-2 text-left transition sm:min-h-24 ${day.current ? 'bg-white hover:bg-[#fcf6f7]' : 'bg-[#fdfbfb] text-[#b5a2a6]'} ${active ? 'ring-2 ring-inset ring-[#9b3b4b]' : ''}`}><span className={`inline-flex h-6 w-6 items-center justify-center rounded-full text-sm ${sameDay(day.date, new Date()) ? 'bg-[#7d1d2b] font-bold text-white' : ''}`}>{day.date.getDate()}</span><div className="mt-1 space-y-1">{dayItems.slice(0, 2).map(item => <span key={item.id} className={`block truncate rounded px-1 py-0.5 text-[10px] font-bold ${colors(item.type)}`}>{item.title}</span>)}</div></button>})}</div></div>
    <aside className="space-y-5"><div className="rounded-2xl border border-[#eadfe1] bg-white p-5"><h2 className="font-bold text-[#4a3036]">{selectedDate.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })}</h2><div className="mt-4 space-y-3">{selectedItems.length ? selectedItems.map(item => <div key={item.id} className="rounded-xl bg-[#fcf5f6] p-3"><div className="flex items-start justify-between gap-2"><p className={`text-xs font-bold uppercase ${typeText(item.type)}`}>{item.type}</p><form action={deleteCalendarItemAction.bind(null, item.id)}><button title="Delete item" className="text-xs text-[#a8888e] hover:text-[#7d1d2b]">Remove</button></form></div><p className="mt-1 font-bold text-[#4a3036]">{item.title}</p><p className="mt-1 text-xs text-[#806d72]">{dateFormatter.format(new Date(item.dueAt))}{item.location ? ` · ${item.location}` : ''}</p>{item.notes && <p className="mt-2 text-xs text-[#806d72]">{item.notes}</p>}</div>) : <p className="rounded-xl bg-[#faf7f6] p-3 text-sm text-[#887277]">Nothing planned for this day yet.</p>}</div></div><form action={formAction} className="rounded-2xl border border-[#eadfe1] bg-white p-5"><h2 className="font-bold text-[#4a3036]">Add to calendar</h2>{state.errors?.form && <p className="mt-3 text-sm text-[#9c2f3e]">{state.errors.form}</p>}<div className="mt-4 space-y-3"><Input label="Title" name="title" placeholder="Chapter meeting" error={state.errors?.title} /><label className="block text-sm font-semibold text-[#644e53]">Type<select name="type" className="mt-1.5 w-full rounded-lg border border-[#e2d7d9] bg-white px-3 py-2 text-sm"><option value="event">Event</option><option value="deadline">Deadline</option><option value="task">Task</option></select></label><Input label="Date & time" name="dueAt" type="datetime-local" defaultValue={localDateTime(selectedDate)} error={state.errors?.dueAt} /><Input label="Location (optional)" name="location" placeholder="Chapter house" /><label className="block text-sm font-semibold text-[#644e53]">Notes<textarea name="notes" className="mt-1.5 min-h-20 w-full rounded-lg border border-[#e2d7d9] px-3 py-2 text-sm" placeholder="Anything helpful to remember?" /></label></div>{state.success && <p className="mt-3 text-sm text-[#46735d]">{state.success}</p>}<button disabled={pending} className="mt-5 w-full rounded-lg bg-[#7d1d2b] px-4 py-2.5 text-sm font-bold text-white hover:bg-[#681522] disabled:opacity-60">{pending ? 'Saving…' : 'Add item'}</button></form></aside>
  </div>;
}

function Input({ label, error, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string; error?: string }) { return <label className="block text-sm font-semibold text-[#644e53]">{label}<input {...props} required={props.name !== 'location'} className="mt-1.5 w-full rounded-lg border border-[#e2d7d9] px-3 py-2 text-sm outline-none focus:border-[#9b3b4b]" />{error && <span className="mt-1 block text-xs font-normal text-[#9c2f3e]">{error}</span>}</label>; }
function makeDays(month: Date) { const start = new Date(month.getFullYear(), month.getMonth(), 1); const first = new Date(start); first.setDate(1 - start.getDay()); return Array.from({ length: 42 }, (_, i) => { const date = new Date(first); date.setDate(first.getDate() + i); return { date, current: date.getMonth() === month.getMonth(), key: date.toISOString() }; }); }
function sameDay(one: Date, two: Date) { return one.getFullYear() === two.getFullYear() && one.getMonth() === two.getMonth() && one.getDate() === two.getDate(); }
function localDateTime(date: Date) { const value = new Date(date); value.setHours(12, 0, 0, 0); const offset = value.getTimezoneOffset(); return new Date(value.getTime() - offset * 60000).toISOString().slice(0, 16); }
function colors(type: string) { return type === 'deadline' ? 'bg-[#f9dfdc] text-[#9a2e3b]' : type === 'task' ? 'bg-[#e8e2fa] text-[#604a9a]' : 'bg-[#e2f3ea] text-[#367354]'; }
function typeText(type: string) { return type === 'deadline' ? 'text-[#9a2e3b]' : type === 'task' ? 'text-[#604a9a]' : 'text-[#367354]'; }
