import Link from "next/link";
import { userLogoutAction } from "@/app/actions";
import { requireApprovedUser } from "@/lib/auth";

const resources = [["NME Slides", "/nme-slides"], ["Health & Education", "/health-education"], ["Academic & Career", "/academic-career"], ["Chapter Information", "/chapter-information"]];
const management = [["Date Feedback Results", "/date-feedback-results"], ["Possible Pairings", "/possible-pairings"]];

export default async function MemberLayout({ children }: { children: React.ReactNode }) { const user = await requireApprovedUser(); return <main className="min-h-screen bg-[#faf7f6] text-[#302327]"><header className="border-b border-[#eadfe1] bg-white px-5 py-4 sm:px-8"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4"><nav className="flex max-w-[75%] items-center gap-1 overflow-visible text-sm font-semibold text-[#6e5a5e]"><Link href="/welcome" className="rounded-lg px-3 py-2 hover:bg-[#f8eeee]">Home</Link><Link href="/big-little-process" className="rounded-lg px-3 py-2 hover:bg-[#f8eeee]">Big/Little</Link><Link href="/finance" className="rounded-lg px-3 py-2 hover:bg-[#f8eeee]">Finance</Link><Menu label="New Member Resources" items={resources} />{user.role === "admin" && <><Menu label="Sister Date Management" items={management} /><Link href="/access-management" className="rounded-lg px-3 py-2 hover:bg-[#f8eeee]">Access Management</Link></>}</nav><div className="flex items-center gap-3 text-right"><div><p className="text-sm font-bold">Hi {user.name.split(" ")[0]}!</p><form action={userLogoutAction}><button className="text-xs text-[#8e777c]">Log out</button></form></div><Link href="/your-profile" className="flex h-10 w-10 items-center justify-center rounded-full bg-[#7d1d2b] text-sm font-bold text-white">{user.name.charAt(0).toUpperCase()}</Link></div></div></header>{children}</main>; }

function Menu({ label, items }: { label: string; items: string[][] }) { return <details className="relative"><summary className="cursor-pointer list-none rounded-lg px-3 py-2 hover:bg-[#f8eeee]">{label} ⌄</summary><div className="absolute left-0 z-30 mt-1 min-w-52 rounded-xl border border-[#eadfe1] bg-white p-1 shadow-lg">{items.map(([name, href]) => <Link key={href} href={href} className="block rounded-lg px-3 py-2 hover:bg-[#f8eeee]">{name}</Link>)}</div></details>; }
