import { CopyCard, NmePage } from "@/components/nme/page";
import { getCurrentUser } from "@/lib/auth";
import { getMemberDateStatus } from "@/lib/member-progress";
import { SisterDateStatus } from "@/components/pairings/sister-date-status";

export default async function BigLittle() {
  const user = await getCurrentUser();
  const assignments = user ? await getMemberDateStatus(user.id) : [];

  return <NmePage title="Big/Little Process"><SisterDateStatus assignments={assignments} /><div className="mt-6 grid gap-6 lg:grid-cols-[.7fr_1.3fr]"><CopyCard title="Schedule"><p>All events, including their location and duration, are in the calendar on the homepage.</p></CopyCard><CopyCard title="Big/Little Process"><p><b>What is a big? What should you be looking for?</b></p><p>A guide, cheerleader, and non-academic role model! Every relationship is different - look for someone who makes you happy.</p><p>You will be paired with a big during reveals, so it is time to get to know the class above you.</p><p>First, fill out the <a className="font-semibold text-[#7d1d2b] underline" href="https://forms.gle/U1PHyTbuBbkJxcfq6" target="_blank" rel="noreferrer">PC 25/26 Profiles</a>. It helps the chapter get to know you and helps you get to know the class above you.</p><p>You will go on 2-3 sister dates a week for the next five weeks. We will also hold Ivy Linkers during NME for you to speed date the sophomores, then you will fill out feedback forms after each date.</p><p>Sophie and Macy will use these forms and feedback to pair you with members you would love, so it is <b>so important</b> to fill them out on time.</p></CopyCard></div><div className="mt-6"><CopyCard title="FAQ"><p><b>What if I feel like I am not finding someone I click with?</b><br />Go to NME Office Hours. The better we know you, the more we can help.</p><p><b>What if I cannot schedule a sister date or have a busy week?</b><br />Let that member know over text, then schedule it for the following week.</p><p><b>How do I pay for sister dates?</b><br />Sister dates are personal, and each member approaches them differently. If sister dates ever put emotional, social, or fiscal stress on you, please text Macy, Sophie, and Saachi to discuss the Inclusivity Fund or more cost-effective approaches.</p></CopyCard></div></NmePage>;
}
